import com.google.gson.GsonBuilder
import com.google.gson.JsonObject
import com.google.gson.JsonParser

plugins {
    id 'eclipse'
    id 'java'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)' apply false
    id 'fabric-loom' version '1.7-SNAPSHOT' apply false
}

subprojects {
    apply plugin: 'java'
    java.toolchain.languageVersion = JavaLanguageVersion.of(17)
    processResources {
        def rawProps = new Properties()
        rootProject.file("gradle.properties").withInputStream { rawProps.load(it) }
        def configProps = new HashMap<>(rawProps)
        inputs.properties(configProps)
        filesMatching(["fabric.mod.json", "META-INF/mods.toml"]) {
            expand(configProps)
        }
    }
}

ext {
    patchRefmaps = { List<String> cfgs, String refMapName, FileCollection outputs ->
        outputs.forEach { path ->
            cfgs.forEach {cfg ->
                File file = new File(path, cfg)
                def jsonElement = JsonParser.parseString(file.text)
                JsonObject json = jsonElement.getAsJsonObject()
                if (!json.has("refmap")) {
                    json.addProperty("refmap", refMapName)
                    file.text = new GsonBuilder().setPrettyPrinting().create().toJson(json)
                }
            }
        }
    }
}