plugins {
    id 'eclipse'
    id 'java'
    id 'net.neoforged.moddev' version '2.0.141' apply false
    id 'net.fabricmc.fabric-loom' version '1.15.4' apply false
}

subprojects {
    apply plugin: 'java'
    java.toolchain.languageVersion = JavaLanguageVersion.of(25)
    processResources {
        def rawProps = new Properties()
        rootProject.file("gradle.properties").withInputStream { rawProps.load(it) }
        def configProps = new HashMap<>(rawProps)
        inputs.properties(configProps)
        filesMatching(["fabric.mod.json", "META-INF/neoforge.mods.toml"]) {
            expand(configProps)
        }
    }
}