modLoader="javafml"
loaderVersion="[2,)"
license="MIT License"

[[mods]]
modId="blockomorph"
version="2.0.1"
displayName="Block'oMorph"
displayURL="https://null.info"
logoFile="logo.png"
credits="."
authors="151gamemode1chit"
description="This mod allows players morph into blocks with all the main features of the block."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.blockomorph]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.223,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.blockomorph]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"




[[mixins]]
    config="mixins.blockomorph.json"