plugins {
    id 'eclipse'
    id 'net.minecraftforge.gradle'
}

base.archivesName = "blockomorph-" + minecraft_version + "-forge-" + mod_version

minecraft {
    mappings channel: 'official', version: minecraft_version
    runs {
        client {
            getArgs().addAll('--username', 'Opa')
        }

        server {

        }

        twoClient {

        }

        configureEach {
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            jvmArgs.add("-Xmx" + min_memoryGb + "G")
            jvmArgs.add("-Xms" + max_memoryGb + "G")
        }
    }
}

dependencies {
    implementation project(':common')

    minecraft "net.minecraftforge:forge:1.20.1-" + forge_loader_version
    implementation(annotationProcessor("io.github.llamalad7:mixinextras-common:0.3.5"))
    jarJar(group: 'io.github.llamalad7', name: 'mixinextras-forge', version: '0.3.5')

    runtimeOnly fileTree(dir: 'run/fabricAdapter', include: ['*.jar'])

    implementation fileTree(dir: 'run/mods', include: ['*.jar'])
    implementation fileTree(dir: 'run/mods/fabricApi', include: ['*.jar'])
}

sourceSets.main.java.srcDirs += project(":common").sourceSets.main.java.srcDirs
sourceSets.main.resources.srcDirs += project(":common").sourceSets.main.resources.srcDirs

jar {
    String outputPath = System.getenv().BLOCKOMORPH_OUTPUT
    if (outputPath != null) destinationDirectory = file(outputPath)
}