plugins {
    id 'eclipse'
    id 'net.neoforged.moddev'
    id 'org.sinytra.adapter.userdev' version '1.2.1-SNAPSHOT'
}

base.archivesName = "blockomorph-" + minecraft_version + "-neoforge-" + mod_version

neoForge {
    version = neoforge_loader_version

    runs {
        client {
            client()
            programArguments.addAll('--username', 'Opa')
        }
        twoClient {
            client()
        }
        server {
            server()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
            jvmArguments.add("-Xmx" + min_memoryGb + "G")
            jvmArguments.add("-Xms" + max_memoryGb + "G")
            disableIdeRun()
        }
    }

    mods {
        testproject {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation project(':common')

    implementation fileTree(dir: 'run/fabricAdapter', include: ['*.jar'])

    implementation fileTree(dir: 'run/mods', include: ['*.jar'])
    implementation fileTree(dir: 'run/mods/fabricApi', include: ['*.jar'])
}

List<String> cfgs = List.of("mixins.blockomorph.json", "mixins.blockomorph.neoforge.json")
String refMapName = base.archivesName.get() + "-refmap.json"

compileJava {
    source(project(":common").sourceSets.main.allSource)
}

processResources {
    from project(':common').sourceSets.main.resources
    doLast {
        patchRefmaps(cfgs, refMapName, outputs.files)
    }
}

jar {
    String outputPath = System.getenv().BLOCKOMORPH_OUTPUT
    if (outputPath != null) destinationDirectory = file(outputPath)
}