plugins {
    id 'net.minecraftforge.gradle'
    id 'org.spongepowered.mixin' version '0.7.+'
}

base.archivesName = "blockomorph-" + minecraft_version + "-forge-" + mod_version

minecraft {
    mappings channel: 'official', version: minecraft_version

    runs {
        client {
        }

        twoClient {
            parent runs.client
            setClient(true)
            getArgs().addAll('--username', 'Opa')
        }

        server {
        }

        configureEach {
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                examplemod {
                    source sourceSets.main
                }
            }
        }
    }
}

dependencies {
    implementation project(':common')
    minecraft "net.minecraftforge:forge:" + minecraft_version + "-" + forge_loader_version
    compileOnly 'org.jetbrains:annotations:24.1.0'

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    annotationProcessor "io.github.llamalad7:mixinextras-common:0.3.5"

    compileOnly "io.github.llamalad7:mixinextras-common:0.3.5"
}

List<String> cfgs = List.of("mixins.blockomorph.json", "mixins.blockomorph.neoforge.json")
String refMapName = base.archivesName.get() + "-refmap.json"
mixin {
    add(sourceSets.main, refMapName)
    cfgs.forEach { cfg -> config(cfg)}
}

jar {
    String outputPath = System.getenv().BLOCKOMORPH_OUTPUT
    if (outputPath != null) destinationDirectory = file(outputPath)
}

compileJava {
    source(project(":common").sourceSets.main.allSource)
}

processResources {
    from project(':common').sourceSets.main.resources
    doLast {
        patchRefmaps(cfgs, refMapName, outputs.files)
    }
}